services:
  # 1. The Backend (FastAPI)
  - type: web
    name: riskpilot-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false # We will get this from Redis Cloud


  # 2. The Frontend (Streamlit)
  - type: web
    name: riskpilot-frontend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port 10000 --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: API_URL
        fromService:
          type: web
          name: riskpilot-backend
          property: url
